### ISSUE TITLE
html5Mode breaks social login.

### ISSUE THREAD

**Issue by garbados** [userapp-io/userapp-angular#4]
https://github.com/userapp-io/userapp-angular/blob/master/angularjs.userapp.js#L784 sets the default oauth callback to use `#/` routing, which breaks if your app doesn't use hash fragment routing, for example if you set `html5Mode(true)`.

**Comment by timothyej** [comment]
I'm looking at this right now, just trying to figure out how to determine the mode (html5 or not, and special hashbang).

**Comment by timothyej** [comment]
This bug is now fixed in the working branch (https://raw.githubusercontent.com/userapp-io/userapp-angular/master/angularjs.userapp.js). 

Please give it a try before I release it as a new version. Thanks for noticing this bug!

**Comment by garbados** [comment]
Wahoo! Thanks for jumping on it so quick! I'll give it a whirl momentarily :D

**Comment by garbados** [comment]
Yep! Works! Thanks!
